### ISSUE TITLE
Flexy-pool with hibernate 4.2

### ISSUE THREAD

**Issue by fmiguelez** [vladmihalcea/flexy-pool#39]
We are using an old version of Hibernate (4.2.14.Final) with JBoss EAP 6.1-Final. 

I wanted to give a try to flexy-pool to test some of the performance hints given by your great book (High-Performance Java Persistence). However when I try to start our application following exception is thrown:

`Caused by: java.lang.NoClassDefFoundError: org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl
`

Is possible to use flexy-pool with Hibernate 4.2?

**Comment by vladmihalcea** [comment]
Prior to Hibernate 4.3, this was the package of `DatasourceConnectionProviderImpl`:

    org.hibernate.service.jdbc.connections.internal.DatasourceConnectionProviderImpl

Since Hibernate 4.3, the package of `DatasourceConnectionProviderImpl` has changed to:

    org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl

The change is fairly simple. You justs have to fork FlexyPool, and change the `FlexyPoolHibernateConnectionProvider` class so that it includes the old package import.

Then, assuming that the modified `FlexyPoolHibernateConnectionProvider` class is located as follows `your.project.package.FlexyPoolHibernate42ConnectionProvider`, you just have to configure the `hibernate.connection.provider_class` Hibernate configuration property alike this:

```
<property name="hibernate.connection.provider_class"
                      value="your.project.package.FlexyPoolHibernate42ConnectionProvider"/>
```

**Comment by fmiguelez** [comment]
I will try this. Thank you very much for your prompt response.

**Comment by vladmihalcea** [comment]
Great! Let me know how it worked for you.

**Comment by fmiguelez** [comment]
Yeah. It worked great! I can see now the statistics via JMX.
